<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>DeskHush.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DeskHush.Core\DeskHush.Core.csproj" />
    <ProjectReference Include="..\..\src\DeskHush.Windows\DeskHush.Windows.csproj" />
  </ItemGroup>

</Project>
